import type { AuthDefinition } from "@w6w/types";
import { buildBody, ENDPOINT, envelope } from "../lib/client.ts";

/**
 * Partner credentials — `partnerUserID` + `partnerUserSecret`, generated at
 * the Integrations page of an Expensify account (Settings > Tools > Integrations); shown once.
 *
 * ## Why `sign` rewrites the body
 *
 * Expensify has no auth header. The credential pair is a `credentials` object INSIDE the JSON
 * held in the `requestJobDescription` form field, so there is nothing for the runtime to stamp
 * on a header. Actions post a job with no `credentials` key; `sign` — the only code handed the
 * secret — parses the form body, replaces `requestJobDescription.credentials` with exactly the
 * two stored fields, and re-serialises it. Every other form field (`template`, `data`) and every
 * other job key is preserved. `credentials` is OVERWRITTEN, never merged, so a job can't smuggle
 * its own `feedUrl`/`sftp`/`authToken` block alongside the stored pair.
 *
 * The documented OAuth2 `authToken` alternative is in private beta and needs a partner
 * `client_id`/`client_secret` registered with Expensify, so it is not offered here.
 *
 * ## The probe
 *
 * `get` / `policyList` — returns the account's policy names, owners and roles; never the
 * credential. HTTP status is useless as a verdict (a bad pair is HTTP 200, measured 2026-10-06):
 * the body's `responseCode` is, and a rejected pair is `404 "Authentication error"`.
 */
export interface PartnerCredential {
  partnerUserID: string;
  partnerUserSecret: string;
}

/** Replace `credentials` inside the job description of a form body. Pure; throws if there is no job. */
export function signBody(body: string | Uint8Array | null | undefined, cred: PartnerCredential) {
  const raw = typeof body === "string" ? body : "";
  const form = new URLSearchParams(raw);
  const jobText = form.get("requestJobDescription");
  if (!jobText) throw new Error("expensify sign: request has no requestJobDescription field");
  let job: Record<string, unknown>;
  try {
    job = JSON.parse(jobText);
  } catch {
    throw new Error("expensify sign: requestJobDescription is not valid JSON");
  }
  job.credentials = {
    partnerUserID: cred.partnerUserID,
    partnerUserSecret: cred.partnerUserSecret,
  };
  form.set("requestJobDescription", JSON.stringify(job));
  return form.toString();
}

const read = (credential: unknown): Partial<PartnerCredential> =>
  (credential ?? {}) as Partial<PartnerCredential>;

const partner: AuthDefinition = {
  key: "partner-credentials",
  type: "custom",
  displayName: "Partner Credentials",
  description:
    "A partnerUserID and partnerUserSecret generated on the Integrations page of an Expensify account (Settings > Tools > Integrations). They are placed inside each request's job description by the connection, never by an action.",
  connectionLabel: "Expensify",
  fields: [
    {
      key: "partnerUserID",
      label: "Partner User ID",
      type: "string",
      required: true,
      placeholder: "aa_user_domain_com",
      hint:
        "From the Integrations page of the Expensify account (Settings > Tools > Integrations).",
    },
    {
      key: "partnerUserSecret",
      label: "Partner User Secret",
      type: "secret",
      required: true,
      hint:
        "Shown only once when generated — generate a new pair if lost. Domain-level jobs (domain cards, reconciliation) need a pair generated by a domain admin.",
    },
  ],

  sign({ request, credential }) {
    const { partnerUserID, partnerUserSecret } = read(credential);
    request.headers["content-type"] = "application/x-www-form-urlencoded";
    request.body = signBody(request.body, {
      partnerUserID: (partnerUserID ?? "").trim(),
      partnerUserSecret: (partnerUserSecret ?? "").trim(),
    });
    return request;
  },

  async test({ credential }, ctx) {
    const { partnerUserID, partnerUserSecret } = read(credential);
    const id = (partnerUserID ?? "").trim();
    const secret = (partnerUserSecret ?? "").trim();
    if (!id) return { ok: false, message: "credential missing partnerUserID" };
    if (!secret) return { ok: false, message: "credential missing partnerUserSecret" };

    let res: Response;
    try {
      res = await ctx.fetch(ENDPOINT, {
        method: "POST",
        headers: {
          accept: "application/json",
          "content-type": "application/x-www-form-urlencoded",
        },
        body: signBody(
          buildBody({ type: "get", inputSettings: { type: "policyList" } }),
          { partnerUserID: id, partnerUserSecret: secret },
        ),
      });
    } catch (e) {
      return { ok: false, message: `could not reach the Expensify Integration Server: ${e}` };
    }

    const text = await res.text().catch(() => "");
    const body = envelope(text);
    const code = typeof body?.responseCode === "number" ? body.responseCode : undefined;

    if (res.ok && code === 200 && Array.isArray(body?.policyList)) return { ok: true };
    if (code === undefined) {
      return {
        ok: false,
        message:
          `Expensify returned ${res.status} without its {responseCode, responseMessage} envelope; the request may not have reached the Integration Server`,
      };
    }
    const vendor = body?.responseMessage ?? "";
    if (code === 404 || /authenticat/i.test(vendor)) {
      return {
        ok: false,
        message:
          `Expensify rejected the partner credentials (${code} ${vendor}). Generate a new pair on the account's Integrations page and reconnect.`,
      };
    }
    if (code === 429 || res.status === 429) {
      return {
        ok: false,
        message: "Expensify rate-limited the check (5 requests/10s, 20/60s); retry shortly.",
      };
    }
    if (code === 200) {
      return { ok: false, message: "policyList answered 200 without a policyList array" };
    }
    return { ok: false, message: `Expensify answered ${code}: ${vendor}` };
  },
};

export default partner;
