import { createAction } from "../lib/actions.ts";

/** The object types an activity may be filed against, verbatim from the API reference. */
const AGAINST = [
  "activity_event",
  "asset",
  "affiliation",
  "account_invoice",
  "account_purchase",
  "contact",
  "contract",
  "contract_period",
  "company",
  "issue",
  "job",
  "milestone",
  "prospect",
  "request",
  "staff",
  "task",
].map((value) => ({ value, label: value }));

export default createAction({
  key: "activity-create",
  resource: "activity",
  path: "/activities",
  title: "Create Activity",
  description:
    "Log a note, call, meeting or email against an object, optionally with billable time. File it against a task to log time on that task.",
  fields: [
    { key: "subject", wire: "subject", label: "Subject", required: true },
    { key: "body", wire: "body", label: "Body", type: "text" },
    {
      key: "againstType",
      wire: "against_type",
      label: "Against type",
      type: "select",
      required: true,
      row: "against",
      options: AGAINST,
    },
    {
      key: "againstId",
      wire: "against_id",
      label: "Against ID",
      type: "number",
      required: true,
      row: "against",
      hint: "The id of the object of the type chosen.",
    },
    {
      key: "medium",
      wire: "medium",
      label: "Medium",
      type: "select",
      options: [
        { value: "note", label: "Note" },
        { value: "meeting", label: "Meeting" },
        { value: "email", label: "Email" },
        { value: "call", label: "Call" },
      ],
      hint: "Defaults to note.",
    },
    {
      key: "details",
      wire: "details",
      label: "Details",
      advanced: true,
      hint: "Location for a meeting, number for a call.",
    },
    {
      key: "priorityId",
      wire: "priority_id",
      label: "Priority ID",
      type: "number",
      advanced: true,
    },
    { key: "classId", wire: "class_id", label: "Class ID", type: "number", advanced: true },
    { key: "taskId", wire: "task_id", label: "Task ID", type: "number", advanced: true },
    {
      key: "ownerType",
      wire: "owner_type",
      label: "Owner type",
      advanced: true,
      row: "owner",
      hint: "`staff` or `affiliation`. Defaults to the connected user.",
    },
    {
      key: "ownerId",
      wire: "owner_id",
      label: "Owner ID",
      type: "number",
      advanced: true,
      row: "owner",
    },
    {
      key: "dateStarted",
      wire: "date_started",
      label: "Started",
      type: "number",
      advanced: true,
      row: "when",
      hint: "Unix timestamp, seconds.",
    },
    {
      key: "dateEnded",
      wire: "date_ended",
      label: "Ended",
      type: "number",
      advanced: true,
      row: "when",
      hint: "Unix timestamp, seconds.",
    },
    {
      key: "billable",
      wire: "billable",
      label: "Billable seconds",
      type: "number",
      advanced: true,
      row: "time",
      hint: "Needs an owner who is staff and an issue, job, milestone, contract or period.",
    },
    {
      key: "nonbillable",
      wire: "nonbillable",
      label: "Non-billable seconds",
      type: "number",
      advanced: true,
      row: "time",
    },
  ],
});
