import { createAction } from "../lib/actions.ts";

export default createAction({
  key: "issue-create",
  resource: "issue",
  path: "/issues",
  title: "Create Issue",
  description: "Open an issue (ticket) against a client or other object.",
  fields: [
    { key: "title", wire: "title", label: "Title", required: true },
    {
      key: "typeId",
      wire: "type_id",
      label: "Issue type ID",
      type: "number",
      hint: "Issue types are configured per deployment — see the API reference's issue types.",
    },
    {
      key: "againstType",
      wire: "against_type",
      label: "Against type",
      row: "against",
      placeholder: "company",
    },
    { key: "againstId", wire: "against_id", label: "Against ID", type: "number", row: "against" },
    { key: "description", wire: "description", label: "Description", type: "text" },
    {
      key: "assignee",
      wire: "assignee",
      label: "Assignee staff ID",
      type: "number",
      hint: "The staff member is assigned and notified.",
    },
    {
      key: "priorityId",
      wire: "priority_id",
      label: "Priority ID",
      type: "number",
      advanced: true,
    },
    { key: "classId", wire: "class_id", label: "Class ID", type: "number", advanced: true },
    {
      key: "affiliationId",
      wire: "affiliation_id",
      label: "Affiliation ID",
      type: "number",
      advanced: true,
    },
    {
      key: "statusId",
      wire: "status_id",
      label: "Status ID",
      type: "number",
      advanced: true,
      row: "status",
      hint: "Preferred over standing; sending both lets standing win.",
    },
    {
      key: "standing",
      wire: "standing",
      label: "Standing",
      advanced: true,
      row: "status",
      hint: "submitted, open, resolved, closed or inactive.",
    },
    {
      key: "dateStarted",
      wire: "date_started",
      label: "Start",
      type: "number",
      advanced: true,
      row: "dates",
      hint: "Unix timestamp, seconds.",
    },
    {
      key: "dateDue",
      wire: "date_due",
      label: "Due",
      type: "number",
      advanced: true,
      row: "dates",
      hint: "Unix timestamp, seconds.",
    },
  ],
});
