import { createAction } from "../lib/actions.ts";

export default createAction({
  key: "job-create",
  resource: "job",
  path: "/jobs",
  title: "Create Job",
  description: "Create a job (project) for a client or other object.",
  fields: [
    { key: "title", wire: "title", label: "Title", required: true },
    {
      key: "typeId",
      wire: "type_id",
      label: "Job type ID",
      type: "number",
      hint: "Required unless a job template supplies it. See the API reference's job types.",
    },
    {
      key: "againstType",
      wire: "against_type",
      label: "Against type",
      row: "against",
      placeholder: "company",
    },
    { key: "againstId", wire: "against_id", label: "Against ID", type: "number", row: "against" },
    { key: "managerId", wire: "manager_id", label: "Manager staff ID", type: "number" },
    {
      key: "affiliationId",
      wire: "affiliation_id",
      label: "Affiliation ID",
      type: "number",
      advanced: true,
    },
    {
      key: "contractId",
      wire: "contract_id",
      label: "Contract ID",
      type: "number",
      advanced: true,
    },
    { key: "statusId", wire: "status_id", label: "Status ID", type: "number", advanced: true },
    {
      key: "jobTemplateId",
      wire: "job_template_id",
      label: "Job template ID",
      type: "number",
      advanced: true,
    },
    {
      key: "dateStarted",
      wire: "date_started",
      label: "Start",
      type: "number",
      advanced: true,
      row: "dates",
      hint: "Unix timestamp, seconds.",
    },
    {
      key: "dateDue",
      wire: "date_due",
      label: "Due",
      type: "number",
      advanced: true,
      row: "dates",
      hint: "Unix timestamp, seconds.",
    },
    { key: "rateId", wire: "rate_id", label: "Rate ID", type: "number", advanced: true },
    {
      key: "isBillable",
      wire: "is_billable",
      label: "Billable",
      type: "boolean",
      bool: "yesno",
      advanced: true,
    },
  ],
});
