import { createAction } from "../lib/actions.ts";

export default createAction({
  key: "task-create",
  resource: "task",
  path: "/tasks",
  title: "Create Task",
  description: "Create a task against an object (typically a job, milestone, issue or company).",
  fields: [
    { key: "title", wire: "title", label: "Title", required: true },
    {
      key: "againstType",
      wire: "against_type",
      label: "Against type",
      row: "against",
      placeholder: "job",
      hint: "The kind of object the task belongs to.",
    },
    { key: "againstId", wire: "against_id", label: "Against ID", type: "number", row: "against" },
    { key: "description", wire: "description", label: "Description", type: "text" },
    {
      key: "assigneeId",
      wire: "assignee_id",
      label: "Assignee staff ID",
      type: "number",
      row: "people",
    },
    {
      key: "managerId",
      wire: "manager_id",
      label: "Manager staff ID",
      type: "number",
      row: "people",
    },
    {
      key: "dateStarted",
      wire: "date_started",
      label: "Start",
      type: "number",
      row: "dates",
      hint: "Unix timestamp, seconds.",
    },
    {
      key: "dateDue",
      wire: "date_due",
      label: "Due",
      type: "number",
      row: "dates",
      hint: "Unix timestamp, seconds.",
    },
    { key: "statusId", wire: "status_id", label: "Status ID", type: "number", advanced: true },
    {
      key: "priorityId",
      wire: "priority_id",
      label: "Priority ID",
      type: "number",
      advanced: true,
    },
    {
      key: "affiliationId",
      wire: "affiliation_id",
      label: "Affiliation ID",
      type: "number",
      advanced: true,
    },
    {
      key: "remaining",
      wire: "remaining",
      label: "Budgeted seconds",
      type: "number",
      advanced: true,
      hint: "Also sets the task's `budgeted` on creation.",
    },
    {
      key: "isBillable",
      wire: "is_billable",
      label: "Billable",
      type: "boolean",
      bool: "yesno",
      advanced: true,
      hint: "Only for tasks against a job or milestone.",
    },
  ],
});
