/**
 * One row per action: the form input, and the single request the action must
 * make. Every URL/body here was checked against the Sellsy OpenAPI document
 * (v2.303.0, 2026-10-06), not derived from the implementation.
 */
export interface Case {
  key: string;
  input: Record<string, unknown>;
  method: string;
  url: string;
  body?: unknown;
  /** Mock response; defaults to a 200 `{pagination, data}` page. */
  response?: { status?: number; body?: unknown };
  /** Result key that must be present in the output. */
  result: string;
}

const B = "https://api.sellsy.com/v2";
const page = {
  status: 200,
  body: { pagination: { limit: 25, count: 1, total: 1, offset: "abc" }, data: [{ id: 7 }] },
};
const obj = { status: 200, body: { id: 7 } };
const none = { status: 204 };

export const cases: Case[] = [
  {
    key: "company-search",
    input: { name: "Acme", type: "client", is_archived: false, id: "1, 2" },
    method: "POST",
    url: `${B}/companies/search?limit=25`,
    body: { filters: { name: "Acme", type: "client", is_archived: false, id: [1, 2] } },
    response: page,
    result: "data",
  },
  {
    key: "company-get",
    input: { id: 7, embed: "main_contact,cf.12" },
    method: "GET",
    url: `${B}/companies/7?embed[]=main_contact&embed[]=cf.12`,
    response: obj,
    result: "company",
  },
  {
    key: "company-create",
    input: {
      name: "Acme",
      type: "prospect",
      legal_france: '{"siret":"12345678901234"}',
      owner_id: "3",
    },
    method: "POST",
    url: `${B}/companies`,
    body: {
      name: "Acme",
      type: "prospect",
      owner_id: 3,
      legal_france: { siret: "12345678901234" },
    },
    response: obj,
    result: "company",
  },
  {
    key: "company-update",
    input: { id: 7, email: "a@b.co" },
    method: "PUT",
    url: `${B}/companies/7`,
    body: { email: "a@b.co" },
    response: obj,
    result: "company",
  },
  {
    key: "company-delete",
    input: { id: 7 },
    method: "DELETE",
    url: `${B}/companies/7`,
    response: none,
    result: "deleted",
  },
  {
    key: "company-contact-link",
    input: { company_id: 7, contact_id: 9, roles: "main,invoicing" },
    method: "POST",
    url: `${B}/companies/7/contacts/9`,
    body: { roles: ["main", "invoicing"] },
    response: none,
    result: "linked",
  },
  {
    key: "individual-search",
    input: { email: "x@y.z", type: ["client"] },
    method: "POST",
    url: `${B}/individuals/search?limit=25`,
    body: { filters: { email: "x@y.z", type: ["client"] } },
    response: page,
    result: "data",
  },
  {
    key: "individual-get",
    input: { id: 7 },
    method: "GET",
    url: `${B}/individuals/7`,
    response: obj,
    result: "individual",
  },
  {
    key: "individual-create",
    input: { type: "client", last_name: "Doe", first_name: "Jo", civility: "mr" },
    method: "POST",
    url: `${B}/individuals`,
    body: { type: "client", last_name: "Doe", first_name: "Jo", civility: "mr" },
    response: obj,
    result: "individual",
  },
  {
    key: "individual-update",
    input: { id: 7, note: "vip" },
    method: "PUT",
    url: `${B}/individuals/7`,
    body: { note: "vip" },
    response: obj,
    result: "individual",
  },
  {
    key: "contact-search",
    input: { last_name: "Doe", companies: "7" },
    method: "POST",
    url: `${B}/contacts/search?limit=25`,
    body: { filters: { last_name: "Doe", companies: [7] } },
    response: page,
    result: "data",
  },
  {
    key: "contact-get",
    input: { id: 9 },
    method: "GET",
    url: `${B}/contacts/9`,
    response: obj,
    result: "contact",
  },
  {
    key: "contact-create",
    input: { last_name: "Doe", position: "CTO" },
    method: "POST",
    url: `${B}/contacts`,
    body: { last_name: "Doe", position: "CTO" },
    response: obj,
    result: "contact",
  },
  {
    key: "contact-update",
    input: { id: 9, mobile_number: "+33600000000" },
    method: "PUT",
    url: `${B}/contacts/9`,
    body: { mobile_number: "+33600000000" },
    response: obj,
    result: "contact",
  },
  {
    key: "opportunity-search",
    input: {
      statuses: "open,late",
      pipeline: "2",
      order: "due_date",
      direction: "desc",
      limit: 10,
      offset: "WyIxMSJd",
    },
    method: "POST",
    url: `${B}/opportunities/search?limit=10&offset=WyIxMSJd&order=due_date&direction=desc`,
    body: { filters: { pipeline: [2], statuses: ["open", "late"] } },
    response: page,
    result: "data",
  },
  {
    key: "opportunity-get",
    input: { id: 5, embed: "company" },
    method: "GET",
    url: `${B}/opportunities/5?embed[]=company`,
    response: obj,
    result: "opportunity",
  },
  {
    key: "opportunity-create",
    input: {
      name: "Deal",
      pipeline: 1,
      step: 2,
      related: [{ id: 7, type: "company" }],
      amount: "1500.00",
      contact_ids: "9",
    },
    method: "POST",
    url: `${B}/opportunities`,
    body: {
      name: "Deal",
      pipeline: 1,
      step: 2,
      related: [{ id: 7, type: "company" }],
      amount: "1500.00",
      contact_ids: [9],
    },
    response: obj,
    result: "opportunity",
  },
  {
    key: "opportunity-update",
    input: { id: 5, status: "won", amount: "2000" },
    method: "PATCH",
    url: `${B}/opportunities/5`,
    body: { status: "won", amount: 2000 },
    response: obj,
    result: "opportunity",
  },
  {
    key: "opportunity-pipelines-list",
    input: { order: "rank" },
    method: "GET",
    url: `${B}/opportunities/pipelines?limit=25&order=rank`,
    response: page,
    result: "data",
  },
  {
    key: "task-search",
    input: { statuses: "todo", labels: "3" },
    method: "POST",
    url: `${B}/tasks/search?limit=25`,
    body: { filters: { statuses: ["todo"], labels: [3] } },
    response: page,
    result: "data",
  },
  {
    key: "task-create",
    input: {
      title: "Call",
      due_date: "2026-11-01T09:00:00+01:00",
      label_id: 3,
      related: '[{"type":"company","id":7}]',
    },
    method: "POST",
    url: `${B}/tasks`,
    body: {
      title: "Call",
      due_date: "2026-11-01T09:00:00+01:00",
      label_id: 3,
      related: [{ type: "company", id: 7 }],
    },
    response: obj,
    result: "task",
  },
  {
    key: "task-update",
    input: { id: 4, status: "done" },
    method: "PUT",
    url: `${B}/tasks/4`,
    body: { status: "done" },
    response: obj,
    result: "task",
  },
  {
    key: "task-labels-list",
    input: {},
    method: "GET",
    url: `${B}/tasks/labels?limit=25`,
    response: page,
    result: "data",
  },
  {
    key: "comment-create",
    input: { description: "Called back", related: [{ type: "company", id: 7 }] },
    method: "POST",
    url: `${B}/comments`,
    body: { description: "Called back", related: [{ type: "company", id: 7 }] },
    response: obj,
    result: "comment",
  },
  {
    key: "estimate-search",
    input: { status: "sent,accepted", currency: "EUR" },
    method: "POST",
    url: `${B}/estimates/search?limit=25`,
    body: { filters: { status: ["sent", "accepted"], currency: "EUR" } },
    response: page,
    result: "data",
  },
  {
    key: "estimate-get",
    input: { id: 11 },
    method: "GET",
    url: `${B}/estimates/11`,
    response: obj,
    result: "estimate",
  },
  {
    key: "estimate-status-update",
    input: { id: 11, status: "accepted" },
    method: "PUT",
    url: `${B}/estimates/11/status`,
    body: { status: "accepted" },
    response: obj,
    result: "estimate",
  },
  {
    key: "invoice-search",
    input: { status: "late", is_deposit: false },
    method: "POST",
    url: `${B}/invoices/search?limit=25`,
    body: { filters: { status: ["late"], is_deposit: false } },
    response: page,
    result: "data",
  },
  {
    key: "invoice-get",
    input: { id: 12 },
    method: "GET",
    url: `${B}/invoices/12`,
    response: obj,
    result: "invoice",
  },
  {
    key: "item-search",
    input: { type: "service", name: "Consulting" },
    method: "POST",
    url: `${B}/items/search?limit=25`,
    body: { filters: { type: ["service"], name: "Consulting" } },
    response: page,
    result: "data",
  },
  {
    key: "item-get",
    input: { id: 13 },
    method: "GET",
    url: `${B}/items/13`,
    response: obj,
    result: "item",
  },
  {
    key: "payment-search",
    input: { status: "confirmed" },
    method: "POST",
    url: `${B}/payments/search?limit=25`,
    body: { filters: { status: ["confirmed"] } },
    response: page,
    result: "data",
  },
  {
    key: "staff-list",
    input: {},
    method: "GET",
    url: `${B}/staffs?limit=25`,
    response: page,
    result: "data",
  },
  {
    key: "webhook-list",
    input: {},
    method: "GET",
    url: `${B}/webhooks?limit=25`,
    response: page,
    result: "data",
  },
  {
    key: "webhook-events-list",
    input: {},
    method: "GET",
    url: `${B}/webhooks/events?limit=25`,
    response: page,
    result: "data",
  },
  {
    key: "webhook-create",
    input: {
      endpoint: "https://hook.example.com/s",
      name: "n",
      events: "task.created, opportunity.created",
      json_content_type: true,
    },
    method: "POST",
    url: `${B}/webhooks`,
    body: {
      type: "http",
      is_enabled: true,
      endpoint: "https://hook.example.com/s",
      configuration: [{ id: "task.created", is_enabled: true }, {
        id: "opportunity.created",
        is_enabled: true,
      }],
      name: "n",
      json_content_type: true,
    },
    response: obj,
    result: "webhook",
  },
  {
    key: "webhook-delete",
    input: { id: 21 },
    method: "DELETE",
    url: `${B}/webhooks/21`,
    response: none,
    result: "deleted",
  },
  {
    key: "quota-get",
    input: {},
    method: "GET",
    url: `${B}/quotas`,
    response: obj,
    result: "quotas",
  },
  {
    key: "search",
    input: { q: "Acme & Sons", type: "company", archived: true },
    method: "GET",
    url: `${B}/search?q=Acme%20%26%20Sons&type=company&limit=25&archived=true`,
    response: page,
    result: "data",
  },
];
