import type { ActionDefinition } from "@w6w/types";
import { buildBody, ENDPOINT, envelope, ExpensifyError, requiredText } from "../lib/client.ts";

interface Input {
  fileName: string;
  fileSystem?: "integrationServer" | "reconciliation";
}

const TEXT = /\.(csv|txt|json|xml)$/i;

function base64(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i += 0x8000) {
    bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }
  return btoa(bin);
}

/** `download` — the Downloader. The response body IS the file, not a JSON envelope. */
const downloadFile: ActionDefinition<Input> = {
  key: "download-file",
  type: "read",
  resource: "file",
  title: "Download File",
  description:
    "Download a file generated by Export Reports or Run Card Reconciliation. Text formats (csv, txt, json, xml) come back as `content`; binary formats (xlsx, xls, pdf) as `contentBase64`.",
  params: [
    {
      key: "fileName",
      label: "File name",
      type: "string",
      required: true,
      hint: "The name returned by the export or reconciliation job.",
    },
    {
      key: "fileSystem",
      label: "File system",
      type: "select",
      default: "integrationServer",
      options: [
        { value: "integrationServer", label: "Report Exporter output (default)" },
        { value: "reconciliation", label: "Reconciliation output" },
      ],
    },
  ],
  output: [
    { key: "fileName", type: "string", label: "File name" },
    { key: "content", type: "string", label: "File text (text formats)" },
    { key: "contentBase64", type: "string", label: "File bytes, base64 (binary formats)" },
    { key: "size", type: "number", label: "Size in bytes" },
  ],

  async execute(input, ctx) {
    const fileName = requiredText("fileName", input.fileName);
    const fileSystem = input.fileSystem ?? "integrationServer";
    if (fileSystem !== "integrationServer" && fileSystem !== "reconciliation") {
      throw new Error("fileSystem must be integrationServer or reconciliation");
    }
    const res = await ctx.fetch(ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/x-www-form-urlencoded" },
      body: buildBody({ type: "download", fileName, fileSystem }),
    });
    const bytes = new Uint8Array(await res.arrayBuffer());
    const head = new TextDecoder().decode(bytes.subarray(0, 2000));

    // A failed download is the JSON error envelope (HTTP 200). A real file never carries both keys.
    const err = TEXT.test(fileName) || head.trimStart().startsWith("{")
      ? envelope(
        new TextDecoder().decode(bytes),
      )
      : null;
    if (
      !res.ok ||
      (err && typeof err.responseCode === "number" && typeof err.responseMessage === "string")
    ) {
      const vendor = err?.responseMessage ?? head.trim().slice(0, 200);
      const code = typeof err?.responseCode === "number" ? err.responseCode : res.status;
      throw new ExpensifyError(
        `Expensify download job failed (${code})${vendor ? `: ${vendor}` : ""}`,
        code,
        vendor,
      );
    }
    if (TEXT.test(fileName)) {
      return { fileName, content: new TextDecoder().decode(bytes), size: bytes.length };
    }
    return { fileName, contentBase64: base64(bytes), size: bytes.length };
  },
};

export default downloadFile;
