import type { AuthDefinition } from "@w6w/types";
import {
  ACCEPT_JSON,
  API_BASE,
  errorText,
  parseJson,
  truncate,
  UNAUTHENTICATED,
} from "../lib/client.ts";

/**
 * ScoreApp Open API key — `Authorization: Bearer <key>`.
 *
 * Verified against "ScoreApp Public API - Getting Started"
 * (`support.scoreapp.com/article/217-scoreapp-public-api-getting-started`, the
 * vendor's only API reference) and a live probe of `open-api.scoreapp.com` on
 * 2026-09-22.
 *
 * ## Bearer header, and there is nothing else
 *
 * The article documents exactly one auth mode — "All API requests use Bearer
 * token authentication", `Authorization: Bearer {token}` — and no OAuth surface
 * exists. The key is generated by the account holder in the ScoreApp UI
 * (Account settings > API keys), shown once at creation, and never retrievable
 * afterwards, which is worth saying in the connection form because a half-saved
 * key cannot be looked up again: it has to be regenerated.
 *
 * ## The probe is `GET /scorecards?limit=1`
 *
 * Three things rule the endpoints in and out:
 *
 * **(a) It must require a credential.** All six documented paths answer
 * `401 {"error":"Unauthenticated."}` with no key (verified live), so any of them
 * works; `/scorecards` is the shortest and returns no per-scorecard data.
 *
 * **(b) It must be cheap.** `?limit=1` asks for one scorecard instead of the
 * default hundred, and the same call is the source of the `quota` health
 * check's `x-ratelimit-*` headers (`../health/rate-limit.ts`), so the two checks
 * share one request.
 *
 * **(c) It must not echo the credential.** None of ScoreApp's documented
 * response shapes contains the API key or any other secret — there is no
 * "current user" or "me" endpoint at all — so no probe here can leak one.
 *
 * ## Classification is from the BODY
 *
 * A bare `401` is not the answer this app reports. ScoreApp documents and sends
 * `{"error":"Unauthenticated."}`, and that string is what {@link apiKey.test}
 * matches before it will say "rejected the key". A `422` on the same call is a
 * query-parameter validation error (this app's bug, not the credential's) and is
 * reported as such, never as an auth failure.
 *
 * ## No `afterConnect`, and no connection label
 *
 * The article documents no account-identity endpoint — no `/me`, no account or
 * organisation object, nothing that would name the connection — and this app does
 * not invent one to get a nicer label. A `connectionLabel` template with no
 * variables to fill would render as literal braces, so it is omitted too.
 */

export interface ScoreAppCredential {
  apiKey: string;
}

/**
 * The one place the wire format is built. Exported so `test` exercises the same
 * code path `sign` does — a hand-rolled second copy is how a probe ends up
 * sending a header the real requests do not.
 */
export function authHeaders(credential: Partial<ScoreAppCredential>): Record<string, string> {
  return { authorization: `Bearer ${credential.apiKey ?? ""}` };
}

/** The credential-liveness probe's path — see the file header for why this one. */
export const PROBE_PATH = "/scorecards";

/** The probe's full URL, including the `limit=1` that keeps it cheap. */
export const PROBE_URL = `${API_BASE}${PROBE_PATH}?limit=1`;

const apiKey: AuthDefinition = {
  key: "api-key",
  type: "bearer",
  displayName: "API Key",
  description:
    "Paste an API key generated in ScoreApp under Account settings > API keys. The full key is " +
    "shown only once, at creation, and cannot be retrieved later.",
  fields: [
    {
      key: "apiKey",
      label: "API Key",
      type: "secret",
      required: true,
      hint: "ScoreApp > Account settings > API keys > add API key. Use a key dedicated to this " +
        "connection rather than one shared with another service, and copy it immediately — " +
        "ScoreApp shows it once and cannot show it again.",
    },
  ],

  /**
   * The only hook handed the raw key, and it runs network-less: it stamps the
   * bearer header and returns. The key never appears in a URL.
   */
  sign({ request, credential }) {
    const cred = credential as Partial<ScoreAppCredential>;
    for (const [name, value] of Object.entries(authHeaders(cred))) {
      request.headers[name] = value;
    }
    return request;
  },

  /** See {@link PROBE_PATH} and the file header for the classification rules. */
  async test({ credential }, ctx) {
    const key = (credential as Partial<ScoreAppCredential>)?.apiKey?.trim() ?? "";
    if (!key) {
      return {
        ok: false,
        message: "credential missing apiKey — connect a ScoreApp API key generated under Account " +
          "settings > API keys.",
      };
    }

    // `Accept: application/json` on purpose, not by habit: without it Laravel
    // answers this unauthenticated request with a 302 to its login page instead
    // of the documented JSON error, and every bad key would be misreported as a
    // network/redirect problem.
    const res = await ctx.fetch(PROBE_URL, {
      headers: { accept: ACCEPT_JSON, ...authHeaders({ apiKey: key }) },
    });
    if (res.ok) return { ok: true };

    const raw = await res.text().catch(() => "");
    const body = parseJson(raw);
    const error = errorText(body);

    // The redirect Laravel serves when a request does not ask for JSON. It is
    // reported as what it is rather than being flattened into "401/302".
    if (res.status >= 300 && res.status < 400) {
      return {
        ok: false,
        message:
          `ScoreApp answered HTTP ${res.status} for ${PROBE_PATH} instead of a JSON error. A ` +
          "redirect to the login page is what this API sends when a request does not carry " +
          "`Accept: application/json` — if you see this, the probe's request shape is wrong, " +
          "not necessarily the key.",
      };
    }

    if (res.status === 401 && error === UNAUTHENTICATED) {
      return {
        ok: false,
        message: "ScoreApp rejected the API key (401 Unauthenticated.): the key is missing, was " +
          "revoked, or was copied incompletely. Generate a new one under Account settings > " +
          "API keys — the full key is shown only once.",
      };
    }
    if (res.status === 401) {
      return {
        ok: false,
        message: `ScoreApp answered 401 for ${PROBE_PATH} without its documented ` +
          `\`{"error":"${UNAUTHENTICATED}"}\` body` +
          `${error ? ` (got "${error}")` : raw ? ` (got ${truncate(raw, 160)})` : ""}. That is ` +
          "not the shape this API sends for a bad key, so treat it as an unexpected refusal " +
          "rather than a revoked credential.",
      };
    }
    if (res.status === 422) {
      return {
        ok: false,
        message:
          `ScoreApp answered 422 Validation Error for the probe's own query (GET ${PROBE_PATH}` +
          `?limit=1)${error ? `: ${error}` : raw ? `: ${truncate(raw, 160)}` : ""}. A 422 is a ` +
          "query-parameter problem in this app, not a credential problem — do not reconnect on " +
          "the strength of it.",
      };
    }
    if (res.status === 429) {
      return {
        ok: false,
        message:
          "ScoreApp rate-limited the probe (429). The Open API answers every response with " +
          "x-ratelimit-limit/x-ratelimit-remaining; wait for the window to roll over and retry.",
      };
    }
    return {
      ok: false,
      message: `ScoreApp returned HTTP ${res.status} for ${PROBE_PATH}?limit=1${
        error ? `: ${error}` : raw ? `: ${truncate(raw, 160)}` : ""
      }`,
    };
  },
};

export default apiKey;
