import type { ActionDefinition } from "@w6w/types";
import { PennylaneClient } from "../lib/client.ts";
import { addressParam, compact, emailsParam, ledgerAccountParam } from "../lib/params.ts";

/**
 * `POST /company_customers` — create a company customer.
 *
 * `name` and a complete `billing_address` are the only required fields.
 * Everything else has a sensible Pennylane default: `external_reference` is
 * generated by the vendor when omitted, `payment_conditions` defaults to
 * `30_days`, and `billing_language` (`fr_FR`, `en_GB`, `de_DE`, `es_ES`)
 * defaults from the company's own locale.
 *
 * A duplicate answers `409` — and unlike most Pennylane errors that body is
 * `{ "status", "error" }` with the human text in `error`.
 *
 * The `201` body is the created customer, including the `id` every later call
 * takes.
 */
interface Input {
  name: string;
  billing_address: Record<string, unknown>;
  vat_number?: string;
  reg_no?: string;
  ledger_account?: Record<string, unknown>;
  phone?: string;
  delivery_address?: Record<string, unknown>;
  payment_conditions?: string;
  billing_iban?: string;
  recipient?: string;
  reference?: string;
  notes?: string;
  emails?: string[];
  external_reference?: string;
  billing_language?: string;
}

/** Pennylane's documented payment-conditions vocabulary. */
const paymentConditionOptions = [
  "upon_receipt",
  "custom",
  "7_days",
  "15_days",
  "30_days",
  "30_days_end_of_month",
  "45_days",
  "45_days_end_of_month",
  "60_days",
].map((value) => ({ value, label: value }));

const createCompanyCustomer: ActionDefinition<Input> = {
  key: "create-company-customer",
  type: "perform",
  resource: "customer",
  title: "Create Company Customer",
  description:
    "Create a company customer with a billing address and optional VAT/registration numbers, " +
    "ledger account and payment conditions (POST /company_customers).",
  idempotent: false,
  params: [
    { key: "name", label: "Company name", type: "string", required: true },
    addressParam("billing_address", "Billing address", true),
    { key: "vat_number", label: "VAT number", type: "string", placeholder: "FR12345678901" },
    {
      key: "reg_no",
      label: "Registration number (SIREN)",
      type: "string",
      placeholder: "123456789",
    },
    ledgerAccountParam(),
    { key: "phone", label: "Phone", type: "string" },
    addressParam("delivery_address", "Delivery address"),
    {
      key: "payment_conditions",
      label: "Payment conditions",
      type: "select",
      options: paymentConditionOptions,
      hint: "Defaults to 30_days at the vendor.",
    },
    { key: "billing_iban", label: "Billing IBAN", type: "string" },
    {
      key: "recipient",
      label: "Recipient",
      type: "string",
      hint: "Who the invoice is addressed to.",
    },
    { key: "reference", label: "Reference", type: "string", advanced: true },
    { key: "notes", label: "Notes", type: "text", advanced: true },
    { ...emailsParam(), advanced: true },
    {
      key: "external_reference",
      label: "External reference",
      type: "string",
      advanced: true,
      hint: "Your own unique id for this customer. Pennylane generates one when omitted.",
    },
    {
      key: "billing_language",
      label: "Billing language",
      type: "select",
      advanced: true,
      options: [
        { value: "fr_FR", label: "French" },
        { value: "en_GB", label: "English" },
        { value: "de_DE", label: "German" },
        { value: "es_ES", label: "Spanish" },
      ],
    },
  ],
  output: [
    { key: "id", type: "number", label: "Customer ID" },
    { key: "name", type: "string", label: "Company name" },
    { key: "billing_address", type: "object", label: "Billing address" },
    { key: "vat_number", type: "string", label: "VAT number" },
    { key: "ledger_account", type: "object", label: "Ledger account" },
    { key: "external_reference", type: "string", label: "External reference" },
  ],

  execute(input, ctx) {
    return new PennylaneClient(ctx).request("/company_customers", {
      method: "POST",
      body: compact(input),
    });
  },
};

export default createCompanyCustomer;
