import type { ActionDefinition } from "@w6w/types";
import { compact, PaystackClient, requireAmount, required, toList } from "../lib/client.ts";

/** `POST /transaction/initialize` — start a checkout; returns the hosted payment page URL. */
interface Input {
  email: string;
  amount: number;
  currency?: string;
  reference?: string;
  callbackUrl?: string;
  channels?: string[] | string;
  plan?: string;
  invoiceLimit?: number;
  splitCode?: string;
  subaccount?: string;
  transactionCharge?: string;
  bearer?: string;
  label?: string;
  metadata?: Record<string, unknown>;
}

const transactionInitialize: ActionDefinition<Input> = {
  key: "transaction-initialize",
  type: "perform",
  resource: "transaction",
  title: "Initialize Transaction",
  description:
    "Create a transaction and get the hosted checkout `authorization_url` to send the customer to. " +
    "Give a unique `reference` to make a retry safe: Paystack refuses a duplicate reference.",
  idempotent: false,
  params: [
    { key: "email", label: "Customer email", type: "string", required: true },
    {
      key: "amount",
      label: "Amount (smallest unit)",
      type: "number",
      required: true,
      hint: "Whole number in kobo/pesewas/cents: 500000 is NGN 5,000.",
      validation: { integer: true, min: 1 },
    },
    {
      key: "currency",
      label: "Currency",
      type: "select",
      hint: "Defaults to the integration's default currency.",
      options: ["NGN", "GHS", "KES", "ZAR", "USD"].map((v) => ({ value: v, label: v })),
    },
    {
      key: "reference",
      label: "Reference",
      type: "string",
      hint: "Unique per transaction. Generated by Paystack when empty.",
    },
    {
      key: "callbackUrl",
      label: "Callback URL",
      type: "string",
      hint: "Overrides the dashboard callback URL.",
    },
    {
      key: "channels",
      label: "Channels",
      type: "multiselect",
      hint: "Restrict the payment channels offered.",
      options: [
        "card",
        "bank",
        "bank_transfer",
        "ussd",
        "mobile_money",
        "qr",
        "eft",
        "apple_pay",
        "capitec_pay",
        "payattitude",
      ].map((v) => ({ value: v, label: v })),
    },
    {
      key: "plan",
      label: "Plan code",
      type: "string",
      hint: "Subscribe the customer to this plan; amount is ignored.",
    },
    {
      key: "invoiceLimit",
      label: "Invoice limit",
      type: "number",
      hint: "Charges to make on the plan.",
      validation: { integer: true, min: 1 },
    },
    { key: "splitCode", label: "Split code", type: "string" },
    { key: "subaccount", label: "Subaccount code", type: "string" },
    {
      key: "transactionCharge",
      label: "Transaction charge",
      type: "string",
      hint: "Flat fee for the main account, overriding the split.",
    },
    {
      key: "bearer",
      label: "Fee bearer",
      type: "select",
      options: [{ value: "account", label: "account" }, {
        value: "subaccount",
        label: "subaccount",
      }],
    },
    { key: "label", label: "Label", type: "string", hint: "Free text shown in the dashboard." },
    {
      key: "metadata",
      label: "Metadata",
      type: "json",
      hint: "Object; `custom_fields` appear in the dashboard.",
    },
  ],
  output: [
    { key: "authorization_url", type: "string", label: "Checkout URL" },
    { key: "access_code", type: "string", label: "Access code" },
    { key: "reference", type: "string", label: "Reference" },
  ],
  async execute(input, ctx) {
    const email = required(input.email, "Customer email");
    const amount = requireAmount(input.amount);
    return await new PaystackClient(ctx).data("/transaction/initialize", {
      method: "POST",
      body: compact({
        email,
        amount,
        currency: input.currency,
        reference: input.reference,
        callback_url: input.callbackUrl,
        channels: toList(input.channels),
        plan: input.plan,
        invoice_limit: input.invoiceLimit,
        split_code: input.splitCode,
        subaccount: input.subaccount,
        transaction_charge: input.transactionCharge,
        bearer: input.bearer,
        label: input.label,
        metadata: input.metadata,
      }),
    });
  },
};

export default transactionInitialize;
