import type { ActionDefinition } from "@w6w/types";
import { compact, MailerooClient, need } from "../lib/client.ts";

interface Input {
  senderProfileId: string;
  channel: string;
  to: string;
  codeLength?: number;
  expiresIn?: number;
}

export const CHANNELS = ["sms", "voice", "whatsapp", "telegram", "email"];

/**
 * `POST /v1/verify/verifications` (scope `verify.verifications.write`) → `202`. This is Maileroo's
 * OTP Verification product: it sends a one-time code to a phone or email address and checks what
 * the user types back. It does NOT validate whether an arbitrary address exists. The code is
 * generated by Maileroo and never returned. Uses the prepaid verification balance (402 when low).
 * The invocation id rides the vendor's `Idempotency-Key` header, so a retried step returns the
 * existing verification instead of texting the user twice.
 */
const sendVerification: ActionDefinition<Input> = {
  key: "send-verification",
  type: "perform",
  idempotent: true,
  resource: "verification",
  title: "Send Verification Code",
  description: "Send a one-time code to a phone number (SMS, voice, WhatsApp, Telegram) or an " +
    "email address through Maileroo OTP Verification. The code is never returned; check what the " +
    "user enters with Check Verification Code. Spends prepaid balance. Account API Key " +
    "(verify.verifications.write).",
  params: [
    {
      key: "senderProfileId",
      label: "Sender profile ID",
      type: "string",
      required: true,
      hint: "`prf_…` — see List Sender Profiles.",
    },
    {
      key: "channel",
      label: "Channel",
      type: "select",
      required: true,
      options: CHANNELS.map((v) => ({ value: v, label: v })),
      hint: "Must be enabled on the sender profile.",
    },
    {
      key: "to",
      label: "Destination",
      type: "string",
      required: true,
      hint: "E.164 phone number (+61412345678) for phone channels, or an email address.",
    },
    {
      key: "codeLength",
      label: "Code length",
      type: "number",
      validation: { min: 4, max: 8, integer: true },
      hint: "4-8 digits; Maileroo defaults to 6.",
    },
    {
      key: "expiresIn",
      label: "Expires in (seconds)",
      type: "number",
      validation: { min: 180, max: 86400, integer: true },
    },
  ],
  output: [
    { key: "id", type: "string", label: "Verification ID (vrf_…)" },
    { key: "status", type: "string", label: "pending until delivery is marked sent" },
    { key: "channel", type: "string", label: "Channel" },
    { key: "to", type: "string", label: "Normalized destination" },
    { key: "country", type: "string", label: "Destination country" },
    { key: "codeLength", type: "number", label: "Code length" },
    { key: "maxAttempts", type: "number", label: "Checks allowed" },
    { key: "expiresAt", type: "string", label: "Expires at (RFC 3339)" },
  ],

  async execute(input, ctx) {
    const channel = need(input.channel, "channel");
    if (!CHANNELS.includes(channel)) {
      throw new Error(`channel must be one of ${CHANNELS.join(", ")}`);
    }
    const key = ctx.invocation?.invocationId;
    const { data } = await new MailerooClient(ctx).account("/verify/verifications", {
      headers: key && /^[\x20-\x7e]{1,200}$/.test(key) ? { "idempotency-key": key } : undefined,
      body: compact({
        sender_profile_id: need(input.senderProfileId, "senderProfileId"),
        channel,
        to: need(input.to, "to"),
        code_length: input.codeLength,
        expires_in: input.expiresIn,
      }),
    });
    const d = (data ?? {}) as Record<string, unknown>;
    return {
      id: d.id,
      status: d.status,
      channel: d.channel,
      to: d.to,
      country: d.country,
      codeLength: d.code_length,
      maxAttempts: d.max_attempts,
      expiresAt: d.expires_at,
    };
  },
};

export default sendVerification;
