import type { ActionDefinition } from "@w6w/types";
import { encodeId, PhraseClient } from "../lib/client.ts";
import { pageOutput, paginationParams } from "../lib/params.ts";

/**
 * `GET /v2/projects/{projectId}/tags` — list a project's tags with how many keys carry each.
 */
interface Input {
  projectId: string;
  branch?: string;
  q?: string;
  excludeSystemTags?: boolean;
  page?: number;
  perPage?: number;
}

const tagList: ActionDefinition<Input> = {
  key: "tag-list",
  type: "search",
  resource: "tag",
  title: "List Tags",
  description: "List a project's tags with how many keys carry each.",
  params: [
    {
      key: "projectId",
      label: "Project ID",
      type: "string",
      required: true,
      hint: "Phrase Strings project id (from List Projects, or the project URL).",
    },
    {
      key: "branch",
      label: "Branch",
      type: "string",
      hint: "Branch name, for projects with branching enabled. Leave empty for the main branch.",
    },
    { key: "q", label: "Name filter", type: "string" },
    {
      key: "excludeSystemTags",
      label: "Exclude system tags",
      type: "boolean",
      hint: "Hide tags generated by jobs, uploads and Figma.",
    },
    ...paginationParams(),
  ],
  output: [...pageOutput],

  execute(input, ctx) {
    return new PhraseClient(ctx).list(`/projects/${encodeId(input.projectId)}/tags`, {
      branch: input.branch,
      q: input.q,
      exclude_system_tags: input.excludeSystemTags,
      page: input.page,
      per_page: input.perPage,
    });
  },
};

export default tagList;
