import type { Param } from "@w6w/types";
import { compact, need } from "./client.ts";

/**
 * Shared request-building for the three sending endpoints (basic, templated, bulk).
 * Field names and limits are the vendor's (Email API > Send Basic Email / Appendix).
 */
export interface EmailObject {
  address: string;
  display_name?: string;
}

/**
 * Recipients arrive as a comma / semicolon / newline separated string (`a@x.com, Jane <j@x.com>`),
 * an array of such strings, or already-shaped `{ address, display_name }` objects.
 * A display name that itself contains a comma cannot be written in the string form: pass the
 * object form (a `json` value) for that.
 */
export function parseRecipients(value: unknown, name: string): EmailObject[] {
  const items: unknown[] = Array.isArray(value)
    ? value
    : typeof value === "string"
    ? value.split(/[;,\n]+/)
    : value && typeof value === "object"
    ? [value]
    : [];
  const out: EmailObject[] = [];
  for (const item of items) {
    if (item && typeof item === "object") {
      const o = item as { address?: unknown; display_name?: unknown };
      const address = String(o.address ?? "").trim();
      if (!address) throw new Error(`${name}: an entry has no address`);
      out.push(compact({ address, display_name: o.display_name as string | undefined }) as never);
      continue;
    }
    const s = String(item ?? "").trim();
    if (!s) continue;
    const m = s.match(/^(.*?)<\s*([^<>\s]+)\s*>$/);
    if (m) {
      const display = m[1].trim().replace(/^"|"$/g, "");
      out.push(compact({ address: m[2], display_name: display }) as never);
    } else {
      out.push({ address: s });
    }
  }
  return out;
}

export function requireRecipients(value: unknown, name: string): EmailObject[] {
  const list = parseRecipients(value, name);
  if (!list.length) throw new Error(`${name} is required`);
  return list;
}

/** An object-valued input given as an object or a JSON string. */
export function asObject(value: unknown, name: string): Record<string, unknown> | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  const v = typeof value === "string" ? JSON.parse(value) : value;
  if (!v || typeof v !== "object" || Array.isArray(v)) {
    throw new Error(`${name} must be a JSON object`);
  }
  return v as Record<string, unknown>;
}

export function asArray(value: unknown, name: string): unknown[] | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  const v = typeof value === "string" ? JSON.parse(value) : value;
  if (!Array.isArray(v)) throw new Error(`${name} must be a JSON array`);
  return v;
}

export function fromObject(address: unknown, name: unknown): EmailObject {
  return compact({
    address: need(address, "fromAddress"),
    display_name: name ? String(name).trim() : undefined,
  }) as unknown as EmailObject;
}

export function checkSubject(subject: unknown): string {
  const s = need(subject, "subject");
  if (s.length > 255) throw new Error("subject must not exceed 255 characters");
  return s;
}

const HEX24 = /^[0-9a-f]{24}$/i;

export function checkReferenceId(value: unknown): string | undefined {
  const v = String(value ?? "").trim();
  if (!v) return undefined;
  if (!HEX24.test(v)) throw new Error("referenceId must be a 24-character hexadecimal string");
  return v;
}

const TRACKING: Param = {
  key: "tracking",
  label: "Open / click tracking",
  type: "boolean",
  hint: "Leave unset to follow the account's setting.",
};
const TAGS: Param = {
  key: "tags",
  label: "Tags",
  type: "json",
  hint:
    'Object of custom tags, e.g. {"campaign":"welcome"}. Keys up to 128 chars, values up to 768.',
};
const HEADERS: Param = {
  key: "headers",
  label: "Custom headers",
  type: "json",
  hint: 'Object, e.g. {"X-Trace-ID":"abc"}. Keys up to 128 chars, values up to 768.',
};
const ATTACHMENTS: Param = {
  key: "attachments",
  label: "Attachments",
  type: "json",
  hint: "Array of { file_name, content (base64), content_type?, inline? }. Max 32 files, " +
    "26.2 MB in total.",
};
const SUBJECT: Param = {
  key: "subject",
  label: "Subject",
  type: "string",
  required: true,
  validation: { maxLength: 255 },
};
const REF: Param = {
  key: "referenceId",
  label: "Reference ID",
  type: "string",
  hint: "Your own 24-character hex ID for tracking; generated by Maileroo when empty.",
};
const SCHEDULED: Param = {
  key: "scheduledAt",
  label: "Schedule for",
  type: "string",
  hint: "RFC 3339 (2026-08-05T11:52:01Z) or natural language (`in 2 hours`). At most 21 days " +
    "ahead. Not available on bulk sends.",
};
const FROM: Param[] = [
  {
    key: "fromAddress",
    label: "From address",
    type: "string",
    required: true,
    hint: "Must be on a domain verified in the Maileroo account.",
  },
  { key: "fromName", label: "From name", type: "string" },
];
const RECIPIENTS: Param[] = [
  {
    key: "to",
    label: "To",
    type: "string",
    required: true,
    hint: "Comma or newline separated. `Jane Smith <jane@example.com>` is accepted.",
  },
  { key: "cc", label: "Cc", type: "string" },
  { key: "bcc", label: "Bcc", type: "string" },
  { key: "replyTo", label: "Reply-To", type: "string" },
];

export const P = {
  TRACKING,
  TAGS,
  HEADERS,
  ATTACHMENTS,
  SUBJECT,
  REF,
  SCHEDULED,
  FROM,
  RECIPIENTS,
};

export interface CommonInput {
  fromAddress: string;
  fromName?: string;
  to: unknown;
  cc?: unknown;
  bcc?: unknown;
  replyTo?: unknown;
  subject: string;
  tracking?: boolean;
  tags?: unknown;
  headers?: unknown;
  attachments?: unknown;
  scheduledAt?: string;
  referenceId?: string;
}

/** The members shared by `/emails` and `/emails/template`. */
export function commonBody(input: CommonInput): Record<string, unknown> {
  const total = [input.to, input.cc, input.bcc].reduce<number>(
    (n, v) => n + parseRecipients(v, "recipients").length,
    0,
  );
  if (total > 500) throw new Error("to, cc and bcc together may hold at most 500 recipients");
  const cc = parseRecipients(input.cc, "cc");
  const bcc = parseRecipients(input.bcc, "bcc");
  const replyTo = parseRecipients(input.replyTo, "replyTo");
  return compact({
    from: fromObject(input.fromAddress, input.fromName),
    to: requireRecipients(input.to, "to"),
    cc: cc.length ? cc : undefined,
    bcc: bcc.length ? bcc : undefined,
    reply_to: replyTo.length ? replyTo : undefined,
    subject: checkSubject(input.subject),
    tracking: typeof input.tracking === "boolean" ? input.tracking : undefined,
    tags: asObject(input.tags, "tags"),
    headers: asObject(input.headers, "headers"),
    attachments: asArray(input.attachments, "attachments"),
    scheduled_at: input.scheduledAt ? String(input.scheduledAt).trim() : undefined,
    reference_id: checkReferenceId(input.referenceId),
  });
}
