import type { AuthDefinition } from "@w6w/types";
import { API_BASE, API_PREFIX } from "../lib/client.ts";

/**
 * Lexware Office API key — `Authorization: Bearer <key>`.
 *
 * Generated by an organization admin at `https://app.lexware.de/addons/public-api`. The key
 * acts for the whole organization; Lexware's docs use "API key" and "access token"
 * interchangeably.
 *
 * ## The probe: `GET /v1/profile`
 *
 * Returns `{organizationId, companyName, created{userId,userName,userEmail,date},
 * connectionId, features, businessFeatures, subscriptionStatus, taxType, smallBusiness}` —
 * organization data and an opaque connection id, never the key. It needs no document scope,
 * so a key limited to some endpoints still passes.
 *
 * Verdicts come from the body, with the status as a hint. Measured 2026-10-06 (no key was
 * available, so the 200 path is from the reference): no header and `Bearer garbage` both
 * answer `401 {"message":"Unauthorized"}` from the AWS gateway; the reference also lists a
 * `403 {"message":"'…' not a valid key=value pair …"}` for a malformed header and
 * `402` for a Lexware contract problem.
 */
export const PROBE_PATH = "/profile";

export interface LexwareCredential {
  apiKey: string;
}

interface Body {
  message?: string;
  companyName?: string;
  subscriptionStatus?: string;
}

export function authHeaders(credential: Partial<LexwareCredential>): Record<string, string> {
  return { authorization: `Bearer ${credential.apiKey ?? ""}` };
}

/** Classify a failed probe from the body's own words; the status is only a hint. */
export async function classifyProbeFailure(res: Response): Promise<{ ok: false; message: string }> {
  const body = await res.json().catch(() => null) as Body | null;
  const msg = typeof body?.message === "string" ? body.message : undefined;
  if (msg && /^unauthorized$/i.test(msg.trim())) {
    return {
      ok: false,
      message: "Lexware rejected the API key (Unauthorized). Check it was copied exactly, has " +
        "not been deleted at app.lexware.de/addons/public-api, and that the API client is enabled.",
    };
  }
  if (msg && /key=value|authorization header/i.test(msg)) {
    return {
      ok: false,
      message: "Lexware could not parse the Authorization header — paste the bare key, " +
        "without a `Bearer ` prefix.",
    };
  }
  if (res.status === 402) {
    return { ok: false, message: "Lexware contract does not permit API access (HTTP 402)" };
  }
  return {
    ok: false,
    message: `Lexware returned HTTP ${res.status}${msg ? ` "${msg}"` : ""} for ${PROBE_PATH}`,
  };
}

const apiKey: AuthDefinition = {
  key: "api-key",
  type: "bearer",
  displayName: "API Key",
  description:
    "Generate an API key at app.lexware.de/addons/public-api (organization admin) and paste it " +
    "here. It acts for the whole organization.",
  connectionLabel: "Lexware Office ({{companyName}})",
  fields: [
    {
      key: "apiKey",
      label: "API Key",
      type: "secret",
      required: true,
      hint: "From app.lexware.de/addons/public-api. Paste the bare key, without `Bearer `.",
    },
  ],

  /** The only hook handed the raw credential; network-less — stamps the header and returns. */
  sign({ request, credential }) {
    for (const [name, value] of Object.entries(authHeaders(credential as LexwareCredential))) {
      request.headers[name] = value;
    }
    return request;
  },

  async test({ credential }, ctx) {
    const key = ((credential as Partial<LexwareCredential>)?.apiKey ?? "").trim();
    if (!key) return { ok: false, message: "credential missing apiKey" };
    // `sign` only auto-applies to action traffic, so the header is built by hand here.
    const res = await ctx.fetch(`${API_BASE}${API_PREFIX}${PROBE_PATH}`, {
      headers: { accept: "application/json", ...authHeaders({ apiKey: key }) },
    });
    if (res.ok) return { ok: true };
    return await classifyProbeFailure(res);
  },

  /** Company name only — the profile's user name and email are left behind. */
  async afterConnect({ credential }, ctx) {
    const key = ((credential as Partial<LexwareCredential>)?.apiKey ?? "").trim();
    try {
      const res = await ctx.fetch(`${API_BASE}${API_PREFIX}${PROBE_PATH}`, {
        headers: { accept: "application/json", ...authHeaders({ apiKey: key }) },
      });
      if (!res.ok) return {};
      const body = await res.json() as Body & { organizationId?: string };
      if (!body?.companyName) return {};
      return { companyName: body.companyName, organizationId: body.organizationId };
    } catch {
      return {};
    }
  },
};

export default apiKey;
