import type { ActionDefinition } from "@w6w/types";
import { GoCardlessClient, type ListPage } from "../lib/client.ts";
import {
  currencyParam,
  dateFilterParams,
  dateFilterQuery,
  enumishParam,
  idFilterParam,
  listOutput,
  paginationParams,
  sortParams,
} from "../lib/params.ts";

/**
 * `GET /payments` — one page of this merchant's payments.
 *
 * The reconciliation workhorse: filter by `status` to find what is still
 * collecting, by `subscription` or `mandate` to attribute a charge, and by
 * `created_at` or `charge_date` to bracket a period. `charge_date` is filtered
 * with the same four bracketed comparisons as `created_at`, because GoCardless
 * documents both as date-filter objects.
 *
 * Note that `status` and `scheme` are free text here (see `list-mandates` for
 * why): the vendor's enum is longer than this app should freeze.
 */
interface Input {
  limit?: number;
  after?: string;
  before?: string;
  currency?: string;
  customer?: string;
  creditor?: string;
  subscription?: string;
  mandate?: string;
  status?: string;
  scheme?: string;
  sortField?: string;
  sortDirection?: string;
  createdAtGt?: string;
  createdAtGte?: string;
  createdAtLt?: string;
  createdAtLte?: string;
  chargeDateGt?: string;
  chargeDateGte?: string;
  chargeDateLt?: string;
  chargeDateLte?: string;
}

const listPayments: ActionDefinition<Input, ListPage<Record<string, unknown>>> = {
  key: "list-payments",
  type: "search",
  resource: "payment",
  title: "List Payments",
  description:
    "Search payments by status, customer, mandate, subscription, currency or date range.",
  params: [
    ...paginationParams(),
    currencyParam(),
    idFilterParam("customer", "Customer ID", "Only payments for this customer."),
    idFilterParam("creditor", "Creditor ID", "Only payments collected by this creditor account."),
    idFilterParam(
      "subscription",
      "Subscription ID",
      "Only payments generated by this subscription.",
    ),
    idFilterParam("mandate", "Mandate ID", "Only payments collected against this mandate."),
    enumishParam(
      "status",
      "Status",
      "GoCardless's own payment `status` values (e.g. `pending_submission`, `submitted`, " +
        "`confirmed`, `paid_out`, `failed`, `cancelled`, `charged_back`).",
    ),
    enumishParam(
      "scheme",
      "Scheme",
      "The bank scheme the payment runs on, e.g. `bacs`, `sepa_core`, `ach`.",
    ),
    ...sortParams("`created_at` (the default) and `charge_date`"),
    ...dateFilterParams({ prefix: "createdAt", label: "Created", field: "created_at" }),
    ...dateFilterParams({ prefix: "chargeDate", label: "Charge date", field: "charge_date" }),
  ],
  output: listOutput,

  execute(input, ctx) {
    return new GoCardlessClient(ctx).list("payments", "/payments", {
      limit: input.limit,
      after: input.after,
      before: input.before,
      currency: input.currency,
      customer: input.customer,
      creditor: input.creditor,
      subscription: input.subscription,
      mandate: input.mandate,
      status: input.status,
      scheme: input.scheme,
      sort_field: input.sortField,
      sort_direction: input.sortDirection,
      ...dateFilterQuery("created_at", {
        gt: input.createdAtGt,
        gte: input.createdAtGte,
        lt: input.createdAtLt,
        lte: input.createdAtLte,
      }),
      ...dateFilterQuery("charge_date", {
        gt: input.chargeDateGt,
        gte: input.chargeDateGte,
        lt: input.chargeDateLt,
        lte: input.chargeDateLte,
      }),
    });
  },
};

export default listPayments;
