import type { ActionDefinition } from "@w6w/types";
import { compact, csv, HOSTS, latLng, MapsClient } from "../lib/client.ts";
import { LANGUAGE_PARAM, REGION_PARAM } from "../lib/params.ts";

/**
 * `POST places.googleapis.com/v1/places:autocomplete` — predictions for a
 * partial string.
 *
 * ## The session token is a billing mechanism, not a nicety
 *
 * Autocomplete is meant to be called on every keystroke, and Google bills it
 * that way — **unless** every request in one typing session carries the same
 * `sessionToken`, and the session is closed by a `place-get` using that same
 * token. Then the whole thing bills once, as a session.
 *
 * Omit the token and each keystroke is a separately-billed request. Reuse a
 * token across unrelated lookups and Google may bill them individually anyway.
 * The token has to be a fresh UUID per session, generated by the caller — this
 * action deliberately does not invent one, because a token this action made up
 * would be discarded before the next keystroke and would achieve exactly
 * nothing while looking like it worked.
 *
 * ## It returns predictions, not places
 *
 * A suggestion is a `placePrediction` with an id and formatted text, or a
 * `queryPrediction` with no place at all — the "restaurants in Soho" kind of
 * suggestion that is a search, not a location. A workflow reading
 * `suggestions[0].placePrediction.placeId` has to cope with the field being
 * absent, which this action does by splitting the two apart.
 */
const action: ActionDefinition = {
  key: "place-autocomplete",
  type: "search",
  resource: "place",
  title: "Autocomplete a place",
  description:
    "Predictions for a partial string. Pass the SAME session token on every keystroke and on " +
    "the closing `place-get`, or Google bills each keystroke separately.",
  params: [
    {
      key: "input",
      label: "Input",
      type: "string",
      required: true,
      default: "",
      hint: "What has been typed so far.",
    },
    {
      key: "sessionToken",
      label: "Session Token",
      type: "string",
      default: "",
      hint: "A UUID your workflow generates once per typing session and reuses on every request " +
        "including the closing `place-get`. Without it, every keystroke is billed on its own.",
    },
    {
      key: "locationBias",
      label: "Bias To",
      type: "string",
      default: "",
      hint: "`lat,lng` — prefers predictions near here.",
    },
    {
      key: "biasRadius",
      label: "Bias Radius (m)",
      type: "number",
      default: 20000,
      showIf: { "!=": [{ var: "locationBias" }, ""] },
    },
    {
      key: "includedPrimaryTypes",
      label: "Types",
      type: "string",
      default: "",
      hint: "Comma-separated. `geocode` or `address` for address entry; `establishment` for " +
        "businesses.",
    },
    {
      key: "includedRegionCodes",
      label: "Only These Countries",
      type: "string",
      default: "",
      hint: "Comma-separated CLDR codes, up to 15 — a hard restriction.",
    },
    {
      key: "includeQueryPredictions",
      label: "Include Query Predictions",
      type: "boolean",
      default: false,
      hint: "Suggestions that are searches rather than places, with no place id at all.",
    },
    LANGUAGE_PARAM,
    REGION_PARAM,
  ],
  output: [
    { key: "predictions", type: "array", label: "Place predictions, each with a place id" },
    { key: "queryPredictions", type: "array", label: "Search suggestions, which have no place" },
    { key: "count", type: "number", label: "Place predictions returned" },
    { key: "sessionToken", type: "string", label: "Pass this to `place-get` to close the session" },
  ],

  async execute(input, ctx) {
    const p = input as Record<string, unknown>;
    const text = String(p.input ?? "").trim();
    if (!text) throw new Error("`input` is required");
    const sessionToken = String(p.sessionToken ?? "").trim();

    const bias = String(p.locationBias ?? "").trim();
    const result = await new MapsClient(ctx).rpc<{
      suggestions?: Array<{
        placePrediction?: { placeId?: string; text?: { text?: string } };
        queryPrediction?: unknown;
      }>;
    }>(HOSTS.places, "/v1/places:autocomplete", {
      method: "POST",
      body: compact({
        input: text,
        sessionToken: sessionToken || undefined,
        includedPrimaryTypes: csv(p.includedPrimaryTypes),
        includedRegionCodes: csv(p.includedRegionCodes),
        includeQueryPredictions: p.includeQueryPredictions === true ? true : undefined,
        languageCode: p.languageCode,
        regionCode: p.regionCode,
        locationBias: bias
          ? {
            circle: {
              center: latLng(bias, "locationBias"),
              radius: Math.max(1, Number(p.biasRadius ?? 20000)),
            },
          }
          : undefined,
      }),
    });

    const suggestions = result?.suggestions ?? [];
    // Two kinds in one array; a caller reading placePrediction blindly gets
    // undefined for the query kind.
    const predictions = suggestions.filter((s) => s?.placePrediction).map((s) => s.placePrediction);
    const queryPredictions = suggestions.filter((s) => s?.queryPrediction).map((s) =>
      s.queryPrediction
    );

    if (!sessionToken) {
      ctx.log(
        "warn",
        "autocompleting without a session token — each request is billed on its own",
        { count: predictions.length },
      );
    }

    return {
      predictions,
      queryPredictions,
      count: predictions.length,
      sessionToken: sessionToken || undefined,
    };
  },
};

export default action;
