import type { ActionDefinition } from "@w6w/types";
import { compact, EasyPostClient, json, sortRates } from "../lib/client.ts";
import type { Rate } from "../lib/client.ts";

/**
 * `POST /v2/pickups` — ask a carrier to come and collect.
 *
 * The other end of the same two-step shape as shipping: creating a pickup
 * **quotes** it, and `pickup-buy` books it. A pickup that is created and never
 * bought is not scheduled, and nobody comes.
 *
 * ## The window is a promise somebody has to keep
 *
 * `min_datetime` and `max_datetime` are when a person will be present to hand
 * the parcels over. Carriers charge for a failed collection, so a window
 * generated by a workflow that does not know the warehouse's hours is a
 * recurring small cost.
 *
 * `is_account_address` is the field that decides whether the driver needs
 * directions: false means an address outside the account's own, and some
 * carriers refuse those entirely.
 */
const action: ActionDefinition = {
  key: "pickup-create",
  type: "perform",
  resource: "pickup",
  title: "Request a pickup quote",
  description:
    "Ask carriers what a collection would cost. This does not book it — `pickup-buy` does, and " +
    "an unbought pickup means nobody comes.",
  idempotent: false,
  params: [
    {
      key: "address",
      label: "Address",
      type: "json",
      required: true,
      default: "",
      hint: "Where the parcels are. Inline or by id.",
    },
    {
      key: "shipmentId",
      label: "Shipment ID",
      type: "string",
      default: "",
      hint: "The purchased shipment being collected. Some carriers require one.",
    },
    {
      key: "minDatetime",
      label: "Window Opens",
      type: "datetime",
      required: true,
      default: "",
      hint: "When somebody will be there. Carriers charge for a failed collection.",
    },
    { key: "maxDatetime", label: "Window Closes", type: "datetime", required: true, default: "" },
    {
      key: "instructions",
      label: "Instructions",
      type: "string",
      default: "",
      hint: "Where the driver should go — a loading bay, a reception desk.",
    },
    {
      key: "isAccountAddress",
      label: "Is the Account Address",
      type: "boolean",
      default: false,
      advanced: true,
      hint: "False means an address outside the account's own; some carriers refuse those.",
    },
  ],
  output: [
    { key: "id", type: "string", label: "Pickup ID — pass it to `pickup-buy`" },
    { key: "pickup_rates", type: "array", label: "What each carrier would charge, cheapest first" },
    { key: "cheapestRate", type: "object", label: "The lowest-priced pickup rate" },
  ],

  async execute(input, ctx) {
    const p = input as Record<string, unknown>;
    const address = json(p.address, "address");
    if (!address) throw new Error("`address` is required");
    const min = String(p.minDatetime ?? "").trim();
    const max = String(p.maxDatetime ?? "").trim();
    if (!min || !max) throw new Error("both `minDatetime` and `maxDatetime` are required");
    if (Date.parse(min) >= Date.parse(max)) {
      throw new Error("the pickup window must open before it closes");
    }

    const pickup = await new EasyPostClient(ctx).request<{
      id?: string;
      pickup_rates?: Rate[];
    }>("/pickups", {
      method: "POST",
      wrapIn: "pickup",
      body: compact({
        address: typeof address === "string" ? { id: address } : address,
        shipment: p.shipmentId ? { id: String(p.shipmentId) } : undefined,
        min_datetime: min,
        max_datetime: max,
        instructions: p.instructions,
        is_account_address: p.isAccountAddress === true ? true : undefined,
      }),
    });

    const rates = sortRates(pickup?.pickup_rates ?? []);
    ctx.log("info", "requested an EasyPost pickup quote", {
      pickupId: pickup?.id,
      rateCount: rates.length,
    });
    return { ...pickup, pickup_rates: rates, cheapestRate: rates[0] };
  },
};

export default action;
