import type { ActionDefinition } from "@w6w/types";
import {
  MailjetClient,
  type MailjetEnvelope,
  PAGE_PARAMS,
  type PageInput,
  pageQuery,
} from "../lib/client.ts";

interface Input extends PageInput {
  name?: string;
  isDeleted?: boolean;
}

/** A v3 `contactslist` object. Field names verified against dev.mailjet.com's reference. */
export interface MailjetContactList {
  ID?: number;
  Name?: string;
  Address?: string;
  CreatedAt?: string;
  IsDeleted?: boolean;
  SubscriberCount?: number;
}

/**
 * List the contact lists on this API key.
 *
 * `IsDeleted` is worth knowing about: Mailjet **soft-deletes** lists. A deleted
 * list keeps its ID and its members and simply stops appearing by default, so a
 * "missing" list is usually flagged rather than gone — pass `isDeleted: true` to
 * see them. That also means list IDs are never recycled, so a stored ID in a
 * workflow stays meaningful.
 *
 * `Address` in the response is not a mailing address: it is a Mailjet-generated
 * address that posts to the list via their SMTP relay ("Unique email address
 * generated by Mailjet, which can be used only via Mailjet's SMTP server").
 */
const listContactLists: ActionDefinition<Input> = {
  key: "list-contact-lists",
  type: "read",
  resource: "contactslist",
  title: "List Contact Lists",
  description:
    "List contact lists (GET /v3/REST/contactslist). Deleted lists are soft-deleted and hidden " +
    "by default — pass `isDeleted` to see them.",
  params: [
    { key: "name", label: "Name", type: "string", hint: "Exact list name to filter by." },
    {
      key: "isDeleted",
      label: "Deleted",
      type: "boolean",
      hint: "True shows soft-deleted lists instead of active ones.",
    },
    ...PAGE_PARAMS,
  ],
  output: [
    { key: "Data", type: "array", label: "Contact lists" },
    { key: "Count", type: "number", label: "Count" },
    { key: "Total", type: "number", label: "Total" },
  ],

  execute(input, ctx) {
    const client = new MailjetClient(ctx);
    return client.v3<MailjetEnvelope<MailjetContactList>>("/contactslist", {
      query: {
        ...pageQuery(input),
        Name: input.name,
        IsDeleted: input.isDeleted,
      },
    });
  },
};

export default listContactLists;
