import type { AuthDefinition } from "@w6w/types";
import { BASE_URL, errorText } from "../lib/client.ts";

interface StoredCredential {
  appSecretToken: string;
  agreementGrantToken: string;
}

/**
 * Two secret tokens — e-conomic identifies the integration (`X-AppSecretToken`, issued to the app
 * by e-conomic) and the customer agreement that granted it access (`X-AgreementGrantToken`, issued
 * when the customer installs the app, or generated by the customer under Settings > Integrations >
 * Access to e-conomic > "Add access"). Both go on every request, set here in `sign`.
 *
 * The probe is `GET /self`: it needs no role beyond a valid grant and answers the agreement
 * (`agreementNumber`, `company`, `user`, `settings`, `modules`, `application`). Checked against
 * the live demo account, the body carries `application.appPublicToken` — the app's PUBLIC token —
 * and neither secret token, so it is safe to call; this check reads only `agreementNumber` and the
 * company name and never returns the body.
 */
const apiKey: AuthDefinition = {
  key: "api-key",
  type: "apiKey",
  displayName: "App Secret Token + Agreement Grant Token",
  description:
    "e-conomic access takes two tokens. The App Secret Token identifies the integration; the Agreement Grant Token is issued by the customer's agreement (Settings > Integrations > Access to e-conomic). Both are sent as headers.",
  connectionLabel: "{{company}} (agreement {{agreementNumber}})",
  apiKey: { in: "header", name: "X-AgreementGrantToken" },
  fields: [
    {
      key: "appSecretToken",
      label: "App Secret Token",
      type: "secret",
      required: true,
      hint:
        "Issued to your integration by e-conomic. Sent as X-AppSecretToken. For evaluation only, the public value `demo` works with a `demo` grant token (read-only).",
    },
    {
      key: "agreementGrantToken",
      label: "Agreement Grant Token",
      type: "secret",
      required: true,
      hint: "Granted by the e-conomic customer for their agreement. Sent as X-AgreementGrantToken.",
    },
  ],

  sign({ request, credential }) {
    const { appSecretToken, agreementGrantToken } = credential as StoredCredential;
    request.headers["x-appsecrettoken"] = appSecretToken;
    request.headers["x-agreementgranttoken"] = agreementGrantToken;
    return request;
  },

  async test({ credential }, ctx) {
    const cred = credential as Partial<StoredCredential>;
    if (!cred.appSecretToken) return { ok: false, message: "credential missing appSecretToken" };
    if (!cred.agreementGrantToken) {
      return { ok: false, message: "credential missing agreementGrantToken" };
    }

    let res: Response;
    try {
      res = await ctx.fetch(`${BASE_URL}/self`, {
        headers: {
          accept: "application/json",
          "x-appsecrettoken": cred.appSecretToken,
          "x-agreementgranttoken": cred.agreementGrantToken,
        },
      });
    } catch (e) {
      return { ok: false, message: `could not reach e-conomic: ${e}` };
    }

    const raw = await res.text().catch(() => "");
    let body: unknown = null;
    try {
      body = raw ? JSON.parse(raw) : null;
    } catch { /* non-JSON: the request probably never reached e-conomic */ }
    const b = body as { agreementNumber?: unknown; message?: unknown } | null;

    // The verdict comes from the body: a live agreement carries a numeric agreementNumber; a
    // rejection carries e-conomic's own {message, errorCode, httpStatusCode}.
    if (res.ok) {
      return typeof b?.agreementNumber === "number" ? { ok: true } : {
        ok: false,
        message: `unexpected ${res.status} body from GET /self — no agreement in it`,
      };
    }
    if (typeof b?.message !== "string") {
      return {
        ok: false,
        message:
          `e-conomic returned ${res.status} with a non-error body; the request may not have reached the API`,
      };
    }
    if (res.status >= 500) {
      return { ok: false, message: `e-conomic is erroring (${res.status}): ${errorText(body)}` };
    }
    return { ok: false, message: errorText(body) };
  },

  /** Names the connection after the company on the agreement. */
  async afterConnect({ credential }, ctx) {
    const cred = credential as Partial<StoredCredential>;
    let company = "e-conomic";
    let agreementNumber: number | undefined;
    try {
      const res = await ctx.fetch(`${BASE_URL}/self`, {
        headers: {
          accept: "application/json",
          "x-appsecrettoken": cred.appSecretToken ?? "",
          "x-agreementgranttoken": cred.agreementGrantToken ?? "",
        },
      });
      if (res.ok) {
        const body = await res.json() as {
          agreementNumber?: number;
          company?: { name?: string };
        };
        if (body.company?.name) company = body.company.name;
        agreementNumber = body.agreementNumber;
      }
    } catch { /* the label falls back to "e-conomic" */ }
    return { company, agreementNumber: agreementNumber ?? "" };
  },
};

export default apiKey;
