import type { ActionDefinition } from "@w6w/types";
import { BigCommerceClient, encodeId } from "../lib/client.ts";
import { orderIdParam } from "../lib/params.ts";

/**
 * `GET /v2/orders/{order_id}/shipping_addresses` — where an order ships.
 *
 * An order can have several: BigCommerce supports splitting one order across
 * destinations, which is why this is a collection rather than a field on the
 * order. Each entry's `id` is the `order_address_id` that `order-shipment-create`
 * requires.
 *
 * Each entry also carries a `shipping_quotes` link. Following it is usually a
 * waste of a call: the vendor documents that quotes can only be generated by the
 * storefront, so for any order created through the API or the control panel that
 * link answers **204 No Content**.
 */
interface Input {
  orderId: number;
  limit?: number;
  page?: number;
}

const orderShippingAddressList: ActionDefinition<Input, { addresses: unknown[] }> = {
  key: "order-shipping-address-list",
  type: "read",
  resource: "order",
  title: "List Order Shipping Addresses",
  description:
    "The shipping destinations on one order. Their `id` is the order_address_id a shipment needs.",
  params: [
    orderIdParam,
    {
      key: "limit",
      label: "Limit",
      type: "number",
      default: 50,
      validation: { integer: true, min: 1, max: 250 },
    },
    { key: "page", label: "Page", type: "number", validation: { integer: true, min: 1 } },
  ],
  output: [{ key: "addresses", type: "array", label: "Shipping addresses" }],

  async execute(input, ctx) {
    const addresses = await new BigCommerceClient(ctx).v2List(
      `/orders/${encodeId(input.orderId)}/shipping_addresses`,
      { query: { limit: input.limit, page: input.page } },
    );
    return { addresses };
  },
};

export default orderShippingAddressList;
