import type { AuthDefinition } from "@w6w/types";
import { API_KEY_HEADER, baseUrl, classifyPing, PING_PATH, type PingBody } from "../lib/client.ts";

/**
 * API key (`X-API-KEY`) — noCRM's account-level scheme.
 *
 * Both halves of the credential are documented in the API document's
 * Authentication section (<https://www.nocrm.io/api>, read 2026-09-22):
 *
 *   - the header is `X-API-KEY`, and
 *   - it is "for the account and it grants you admin rights. Meaning if you
 *     create a lead for example with this api key without specifying a user,
 *     the lead won't belong to any specific user and will appear in the
 *     interface as an unassigned lead."
 *
 * The document also states the same key may be sent as a request *parameter*
 * instead of a header, and warns that the API answers only over https. This app
 * only ever uses the header: a workflow host logs request URLs but not request
 * headers, so the query form is the one shape that would leak the key.
 *
 * ## The subdomain is collected here, not per-action
 *
 * Every account has its own host (`https://<subdomain>.nocrm.io`), so the
 * subdomain identifies the account and belongs to the Connection.
 * `afterConnect` records it on the connection's redacted `display`, which is
 * where `lib/client.ts` reads it from — so no Action ever handles it.
 *
 * ## The probe
 *
 * `GET /api/v2/ping` is the document's own "make sure that the key to
 * authenticate the requests is correct" endpoint. It returns
 * `{"status":200,"message":"Your API key is correct."}` — a whoami with no
 * credential in it — and it is classified by `classifyPing` from the body, not
 * from the status code.
 */
const apiKey: AuthDefinition = {
  key: "api-key",
  type: "apiKey",
  apiKey: { in: "header", name: API_KEY_HEADER },
  displayName: "API Key",
  description:
    "Connect with your noCRM account API key. Create one from the admin section of your " +
    "account. It is account-level and grants admin rights.",
  connectionLabel: "{{subdomain}}.nocrm.io",
  fields: [
    {
      key: "subdomain",
      label: "Subdomain",
      type: "string",
      required: true,
      placeholder: "acme",
      hint: "Just the subdomain from `acme.nocrm.io` — not the full URL.",
      validation: { pattern: "^[a-zA-Z0-9-]+$" },
    },
    {
      key: "apiKey",
      label: "API Key",
      type: "secret",
      required: true,
      hint: "Generated by your administrator from the admin section of your noCRM account.",
    },
  ],

  sign({ request, credential }) {
    const { apiKey } = credential as { apiKey: string };
    request.headers[API_KEY_HEADER] = apiKey;
    return request;
  },

  async test({ credential }, ctx) {
    const { subdomain, apiKey } = credential as { subdomain?: string; apiKey?: string };
    if (!subdomain || !apiKey) {
      return { ok: false, message: "credential missing subdomain or apiKey" };
    }
    const res = await ctx.fetch(`${baseUrl(subdomain)}${PING_PATH}`, {
      headers: { [API_KEY_HEADER]: apiKey },
    });
    // Read the body first: the classification is the vendor's own error code,
    // not the status code, per the document's Errors section.
    const body = await res.json().catch(() => ({})) as PingBody;
    return classifyPing(res.status, body);
  },

  /**
   * Records the subdomain on the connection so the client can build URLs
   * without ever seeing the credential. No request is made: the ping answers no
   * account metadata, so there is nothing to fetch that `test` has not just
   * answered.
   */
  afterConnect({ credential }) {
    const { subdomain } = credential as { subdomain?: string };
    if (!subdomain) return {};
    return { subdomain };
  },
};

export default apiKey;
