import type { ActionDefinition } from "@w6w/types";
import { CloseClient, compact } from "../lib/client.ts";

interface Input {
  leadId: string;
  text: string;
  type?: string;
  assignedTo?: string;
  date?: string;
  isComplete?: boolean;
  isDateless?: boolean;
  priority?: string;
}

/**
 * `POST /task/` — create a Task.
 *
 * ## Only two types can be created
 *
 * Close's create page is explicit: "Currently only tasks of type `lead` and
 * `outgoing_call` can be created." The other seven types in the vocabulary
 * (`missed_call`, `voicemail`, `incoming_email`, `email_followup`,
 * `incoming_sms`, `opportunity_due`, `answered_detached_call`) are generated by
 * Close itself in response to real events and cannot be minted through the API.
 * The `type` param therefore offers exactly the two creatable values rather than
 * the full list — offering the rest would only produce rejections.
 *
 * `_type` defaults to `lead` here, which is the ordinary "to-do on an account"
 * task and by far the common case.
 *
 * ## `date`, not `due_date`
 *
 * Close deprecated `due_date` — "should not be used". `date` is the live field
 * and means "when the task is actionable and appears in the inbox". It accepts
 * either a plain date (`2026-01-05`) or a date-time
 * (`2026-01-05T05:00:00+00:00`).
 *
 * `is_dateless` covers the genuinely undated to-do, which is a different thing
 * from one dated today.
 *
 * Not idempotent: a retry creates a second, identical task.
 */
const createTask: ActionDefinition<Input> = {
  key: "create-task",
  type: "perform",
  resource: "task",
  title: "Create Task",
  description:
    "Create a Task on a Lead. Only `lead` and `outgoing_call` types can be created via the API — " +
    "Close generates the rest itself.",
  idempotent: false,
  params: [
    { key: "leadId", label: "Lead ID", type: "string", required: true, placeholder: "lead_..." },
    {
      key: "text",
      label: "Text",
      type: "text",
      required: true,
      placeholder: "Connect with Account Manager",
      hint: "What the task says in the rep's inbox.",
    },
    {
      key: "type",
      label: "Task type",
      type: "select",
      default: "lead",
      options: [
        { value: "lead", label: "Lead (to-do)" },
        { value: "outgoing_call", label: "Outgoing call" },
      ],
      hint: "The only two types the API can create. Everything else is generated by Close.",
    },
    {
      key: "assignedTo",
      label: "Assigned to (User ID)",
      type: "string",
      placeholder: "user_...",
      hint: "Whose inbox this lands in. Get ids from the List Users action.",
    },
    {
      key: "date",
      label: "Date",
      type: "string",
      placeholder: "2026-01-05",
      hint: "When the task becomes actionable. Date (`2026-01-05`) or date-time " +
        "(`2026-01-05T05:00:00+00:00`). This is Close's live field — `due_date` is deprecated.",
    },
    {
      key: "isDateless",
      label: "Is dateless",
      type: "boolean",
      hint: "For a to-do with no date at all, which is distinct from one dated today.",
    },
    {
      key: "isComplete",
      label: "Is complete",
      type: "boolean",
      hint: "Create it already done — useful when backfilling historical work.",
    },
    {
      key: "priority",
      label: "Priority",
      type: "select",
      options: [
        { value: "high", label: "High" },
        { value: "medium", label: "Medium" },
      ],
      hint: "Close's documented priority vocabulary is just these two; omit for normal.",
    },
  ],
  output: [{ key: "id", type: "string", label: "Task ID" }],

  execute(input, ctx) {
    return new CloseClient(ctx).request("/task/", {
      method: "POST",
      body: compact({
        _type: input.type ?? "lead",
        lead_id: input.leadId,
        text: input.text,
        assigned_to: input.assignedTo,
        date: input.date,
        is_dateless: input.isDateless,
        is_complete: input.isComplete,
        priority: input.priority,
      }),
    });
  },
};

export default createTask;
